### ISSUE TITLE
Godot 4 compatibility

### ISSUE THREAD

**Issue by hinode-codes** [poohcom1/godot-animated-sprite-2-player#14]
Hello. I tried to use this, but the written code is not compatible with Godot 4.

**Comment by poohcom1** [comment]
It should be compatible with version 4, atleast version 4.0. Did you download from this link: https://godotengine.org/asset-library/asset/1605?

**Comment by hinode-codes** [comment]
Ohh, I didn't know there was one for v4.0, I'll check it out and retract my PR soon. Thank you!

**Comment by hinode-codes** [comment]
> It should be compatible with version 4, atleast version 4.0. Did you download from this link: https://godotengine.org/asset-library/asset/1605?

I downloaded the one with a 3.5 tag and didn't see any other versions. I then checked this repo, and downloaded the ZIP file.
