### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by Snorrd** [poohcom1/godot-animated-sprite-2-player#20]
So i downloaded this addon, and the convert button wouldn't appear. I found out that some of the files were missing or godot couldn't find them. Maybe this screenshot could tell whats wrong
![image](https://github.com/user-attachments/assets/cbb9d8df-791c-411e-bed2-eee38567cbf6)
This addon worked perfectly on older godot versions, but in newer versions (4.3) it wont work

**Comment by poohcom1** [comment]
The path in your output shows that the folder got placed in the wrong directory. Move `addons/AS2P` to your root folder, i.e. `res://addons/AS2P`.

**Comment by Snorrd** [comment]
> The path in your output shows that the folder got placed in the wrong directory. Move `addons/AS2P` to your root folder, i.e. `res://addons/AS2P`.

it is in the root folder, i moved it earlier but still couldn't help
![image](https://github.com/user-attachments/assets/96681cb1-bec4-4716-9eca-1250e57245d8)

**Comment by poohcom1** [comment]
Are the error messages the same when in root?

**Comment by Snorrd** [comment]
> Are the error messages the same when in root?

errors with "couldn't find the file" are gone, but the parse errors still there:
* failed to load script "plugin.gd"
* "Convertor" is a constant but does not contain a type

after re-downloading the addon the error messages were gone for a while, but converting button wasn't appearing in the anim player inspector

**Comment by poohcom1** [comment]
I can't seem to replicate it on my side, but based on your errors from the pic it's probably related to these lines in `NodeSelectorProperty.gd`. Can you try deleting them and reloading?

![image](https://github.com/user-attachments/assets/3faaff8c-8f08-4f64-83d1-b1b098b222df)

**Comment by Snorrd** [comment]
> I can't seem to replicate it on my side, but based on your errors from the pic it's probably related to these lines in `NodeSelectorProperty.gd`. Can you try deleting them and reloading?
> 
> ![image](https://private-user-images.githubusercontent.com/74857873/393341352-3faaff8c-8f08-4f64-83d1-b1b098b222df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1MDUyNjUsIm5iZiI6MTczMzUwNDk2NSwicGF0aCI6Ii83NDg1Nzg3My8zOTMzNDEzNTItM2ZhYWZmOGMtOGYwOC00ZjY0LTgzZDEtYjFiMDk4YjIyMmRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDE3MDkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzMzE0ZTg4NzFiYmU5OTA5OGU0MTgxY2M2ZjQ4MzcwYjUxMWFiNjBjNTgyNDRlMGFlODk5YTUzYTQ0Njk2Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5Y7hsO2NkXz8Bdc-WgV_RYFXWeKwQC0flwJkij4BGXo)

i've done exactly as you said, deleted these lines and reloaded the project. but still the addon wont work
kinda weird

(no error lines in output)

**Comment by poohcom1** [comment]
Hmm, that is kinda weird, not sure how else I can debug it. Can you upload an example project with the issue?

**Comment by Snorrd** [comment]
i just fixed the issue😭the plugin was automatically disabled in project settings, that was stupid
anyways im sorry for the time waste and thank you for the help
