### ISSUE TITLE
godot 4.2 crash , play game and open animationplayer 

### ISSUE THREAD

**Issue by Zifai** [poohcom1/godot-animated-sprite-2-player#9]

**Comment by poohcom1** [comment]
Can you specify which 4.2 version?

**Comment by Zifai** [comment]
4.2 beta 4

**Comment by poohcom1** [comment]
Are you still able to reproduce this issue in the latest stable version? I've tested on 4.2.1 and found no issues.

**Comment by poohcom1** [comment]
I'm closing this issue for now, if you can reproduce it, feel free to reopen or create a new one.
